version: '3'

services:
  app:
    build: .
    image: napat/app:1.0.0
    container_name: tct-app-strapi
    restart: always
    ports:
      - ${APP_PORT}
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    depends_on:
      - db
    
    
  db:
    image: postgres
    container_name: tct-app-postgres
    restart: always
    #ports:
    #  - ${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    
    
